in:
  type: file
  path_prefix: /Users/k_morishita/Documents/workspace/embulk_plugins/embulk-parser-regex/sample/data_
  parser:
    charset: UTF-8
    newline: LF
    type: regex
out: 
  type: stdout

