in:
  type: file
  path_prefix: /Users/k_morishita/Documents/workspace/embulk_plugins/embulk-parser-regex/sample/apache_1/data_apache_
  parser:
    charset: UTF-8
    newline: LF
out:
  type: stdout

